layout_spectrum: 0.8969088
color:
  saturation: 0.2921147
  brandStrength: 0.4204907
  lightness: 0.7049081
  rhythmicContrast: 0.5364505
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
typography_spectrum: 0.5894367
name: Madam Mirkin
